# Generated by Django 3.1.4 on 2020-12-01 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Name should be 3 chars long'), django.core.validators.MaxLengthValidator(50, 'Name shoild not be longer than 50 chars')], verbose_name='NAME')),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Name should be 5 chars long'), django.core.validators.MaxLengthValidator(50, 'Name shoild not be longer than 50 chars'), django.core.validators.EmailValidator('Invalid Email')], verbose_name='EMAIL')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(20, 'Age should be above 20'), django.core.validators.MaxValueValidator(70, 'Age should be below 70')], verbose_name='AGE')),
                ('phone', models.BigIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(6666666666, 'Invalid Phone Number'), django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number')], verbose_name='PHONE')),
                ('role', models.CharField(choices=[('Senior Developer', 'Senior Developer'), ('Junior Developer', 'Junior Developer'), ('Software Tester', 'Software Tester')], max_length=100, verbose_name='ROLE')),
                ('address', models.CharField(default=0, max_length=255, verbose_name='ADDRESS')),
            ],
        ),
    ]
